apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavendeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mavenapp
  template:
    metadata:
      labels:
        app: mavenapp
    spec:
      containers:
      - name: mavencontainer
        image: senoritahub/maven-web-application:1
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
--- 
apiVersion: v1
kind: Service
metadata:
  name: mavensvc
spec:
  type: Nodeport
  selector:
    app: mavenapp
  ports:
  - port: 80
    targetPort: 8080
